- name: "Demo client-server on Openstack"
  hosts: all
  become: false
  gather_facts: no
  tasks:
  - name: "Download image"
    get_url:
      url: "{{demo_image_url}}"
      dest: /tmp/vish_image.qcow2
      mode: '0440'
  - name: "Upload Centos Image"
    openstack.cloud.image:
      auth:
        auth_url: "{{osp_auth_url}}"
        username: "{{osp_username}}"
        password: "{{osp_password}}"
        project_name: "{{osp_project_name}}"
        os_user_domain_name: "{{osp_user_domain_name}}"
        os_project_domain_name: "{{osp_project_domain_name}}"
      name: vish_image
      container_format: bare
      disk_format: qcow2
      state: present
      filename: /tmp/vish_image.qcow2
      kernel: cirros-vmlinuz
      ramdisk: cirros-initrd
      tags:
        - demo
      properties:
        cpu_arch: x86_64
        distro: ubuntu
  - name: "Create Network"
    openstack.cloud.network:
      auth:
        auth_url: "{{osp_auth_url}}"
        username: "{{osp_username}}"
        password: "{{osp_password}}"
        project_name: "{{osp_project_name}}"
        os_user_domain_name: "{{osp_user_domain_name}}"
        os_project_domain_name: "{{osp_project_domain_name}}"
      state: present
      name: vish_network
      shared: yes
      provider_network_type: vxlan
      provider_segmentation_id: 5
      external: false

  - name: "Create subnet"
    openstack.cloud.subnet:
      auth:
        auth_url: "{{osp_auth_url}}"
        username: "{{osp_username}}"
        password: "{{osp_password}}"
        project_name: "{{osp_project_name}}"
        os_user_domain_name: "{{osp_user_domain_name}}"
        os_project_domain_name: "{{osp_project_domain_name}}"
      state: present
      network_name: vish_network
      name: vish_subnet
      cidr: 192.168.0.0/24
      enable_dhcp: yes
      allocation_pool_start: '192.168.0.100'
      allocation_pool_end: '192.168.0.102'

  - name: "Create flavor with 1024MB of RAM, 1 virtual CPU, and 12GB of local disk."
    openstack.cloud.compute_flavor:
      auth:
        auth_url: "{{osp_auth_url}}"
        username: "{{osp_username}}"
        password: "{{osp_password}}"
        project_name: "{{osp_project_name}}"
        os_user_domain_name: "{{osp_user_domain_name}}"
        os_project_domain_name: "{{osp_project_domain_name}}"
      state: present
      name: vish_flavor
      ram: 1024
      vcpus: 1
      disk: 12
  - name: "launch web-server instance"
    openstack.cloud.server:
      name: vm-server
      state: present
      auth:
        auth_url: "{{osp_auth_url}}"
        username: "{{osp_username}}"
        password: "{{osp_password}}"
        project_name: "{{osp_project_name}}"
        os_user_domain_name: "{{osp_user_domain_name}}"
        os_project_domain_name: "{{osp_project_domain_name}}"
      image: "vish_image"
      flavor: "vish_flavor"
      network: "vish_network"
      userdata: |
        #cloud-config:
        password: demopasswd
        chpasswd: { expire: False }
        ssh_pwauth: True
        runcmd:
          - nohup bash -c 'while true;do echo -e "HTTP/1.1 200 OK\r\n$(date)\r\n\r\nHello from $(hostname) on $(date)" | nc -l 8080 -q 1;done' &
        bootcmd:
          - echo "Boot Completed"
    register: vm1

  - name: "launch client instance"
    openstack.cloud.server:
      name: vm-client
      state: present
      auth:
        auth_url: "{{osp_auth_url}}"
        username: "{{osp_username}}"
        password: "{{osp_password}}"
        project_name: "{{osp_project_name}}"
        os_user_domain_name: "{{osp_user_domain_name}}"
        os_project_domain_name: "{{osp_project_domain_name}}"
      image: "vish_image"
      flavor: "vish_flavor"
      network: "vish_network"
      userdata: |
        #cloud-config:
        password: demopasswd
        chpasswd: { expire: False }
        ssh_pwauth: True
        runcmd:
                - nohup bash -c 'while true;do curl {{vm1.openstack.addresses.vish_network[0].addr}}:8080 2>/dev/null;sleep 5;done' &
        bootcmd:
          - echo "Boot Completed"
