apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: admin
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: cluster-admin-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rhosplab
  name: osp-redirect
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rhosplab
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rhosplab
      name: osp-redirect
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
        imagePullPolicy: IfNotPresent
        name: horizon
        readinessProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 4     
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        command:
        - bash
        - -c
        - |
          yum install https://rpmfind.net/linux/epel/8/Everything/x86_64/Packages/s/sshpass-1.06-9.el8.x86_64.rpm -y
          sshpass -p "$SSHPASS" ssh -vNT -L 0.0.0.0:8080:192.0.2.252:8181 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $workstation
        env:
        - name: workstation
          value: "avishnia-redhat.com@workstation-069c.dynamic.opentlc.com"
        - name: SSHPASS
          value: "WRuqpgfEqt0o"
      - image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
        imagePullPolicy: IfNotPresent
        name: vnc
        readinessProbe:
          tcpSocket:
            port: 6080
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 4     
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        command:
        - bash
        - -c
        - |
          yum install https://rpmfind.net/linux/epel/8/Everything/x86_64/Packages/s/sshpass-1.06-9.el8.x86_64.rpm -y
          sshpass -p "$SSHPASS" ssh -vNT -L 0.0.0.0:6080:192.0.2.252:8282 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $workstation
        env:
        - name: workstation
          value: "avishnia-redhat.com@workstation-069c.dynamic.opentlc.com"
        - name: SSHPASS
          value: "WRuqpgfEqt0o"
      - image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
        imagePullPolicy: IfNotPresent
        name: keystone
        readinessProbe:
          tcpSocket:
            port: 5000
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 4     
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        command:
        - bash
        - -c
        - |
          yum install https://rpmfind.net/linux/epel/8/Everything/x86_64/Packages/s/sshpass-1.06-9.el8.x86_64.rpm -y
          sshpass -p "$SSHPASS" ssh -vNT -L 0.0.0.0:5000:192.0.2.252:8383 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $workstation
        env:
        - name: workstation
          value: "avishnia-redhat.com@workstation-069c.dynamic.opentlc.com"
        - name: SSHPASS
          value: "WRuqpgfEqt0o"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: admin
      securityContext:
        privileged: true
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: osp-rhocplab
  namespace: default
spec:
  ports:
  - port: 8080
    name: horizon
    protocol: TCP
    targetPort: 8080
  - port: 6080
    name: vnc
    protocol: TCP
    targetPort: 6080
  - port: 5000
    name: keystone
    protocol: TCP
    targetPort: 5000
  selector:
    app: rhosplab
  sessionAffinity: None
  type: ClusterIP
